### ISSUE TITLE
天呢！SakuraFrp真的好好用

### ISSUE THREAD

**Issue by zcm2005** [fengberd/SakuraFrpLauncher#1]
竟然是全免费的内网穿透，速度比起nat123的免费通道都快很多啊，天啊这简直是在做公益，真的好感谢。但是可以让登录的TextBox明显一点吗……找了好久QAQ

**Comment by fengberd** [comment]
一进去应该就是设置页面吧, 语言也会自动获取系统语言设为中文
应该够明显了..
