### ISSUE TITLE
能否分隧道显示日志？

### ISSUE THREAD

**Issue by lensferno** [fengberd/SakuraFrpLauncher#10]
隧道一多了之后，不同隧道的日志信息全都挤在了一起，看着有点眼花，有点难分清

**Comment by fengberd** [comment]
日志过滤功能在开发计划中，但目前没有时间写

**Comment by fengberd** [comment]
已在 https://github.com/fengberd/SakuraFrpLauncher/commit/2810eb7c5a0ce1eeb09eee8778cf6a79712bcdbb 中实现，但是由于还有其他计划中的功能，暂时不会推送新版。你可以自己编译来获取这个特性
