### ISSUE TITLE
疑似内存溢出bug【极其严重】

### ISSUE THREAD

**Issue by Stehsaer** [fengberd/SakuraFrpLauncher#12]
时间：2021.7.22 凌晨
发生频率：偶然
严重性：**极高**（殃及全操作系统）
本电脑配置：
- CPU：AMD R9 4900X
- 内存：32GB
- 操作系统：Windows 10

frp版本：SakuraFrpLauncher 2.0.4.0

描述：frp进程过度占用内存（17.4G），导致系统内存不足。程序运行时长约10小时。frp已经确认为最新版本。出现问题时frp状况：似乎只有一条隧道开着

猜测：GC出错导致无法清除垃圾
日志：无法找到日志

请尽快处理

**Comment by fakeboboliu** [comment]
您好，首先请确认发生问题的进程是 frpc（注意c），还是有头像图标的启动器。

如果是启动器，我们在最近的 [commit](https://github.com/natfrp/SakuraFrpLauncher/commit/0bc56547b77e6ab7be17fa484e17bfdd0d46cfab) 修复了一个可能的内存泄露问题，但是暂时还没有发布。
如果您没有自己编译dev分支的工具的话，可以选择不要让启动器常驻后台，在启动需要的隧道后右击启动器图标，选择 “退出启动器” 即可，隧道会继续工作，再次打开启动器即可查看运行情况等。

如果是frpc的话，目前您的问题我们无法复现，如果您可以在发生问题的时候打开 任务管理器 - “详细信息” 找到出现问题的进程，右键创建转储文件，然后联系我们的话，将大大提前我们发现问题的进程。

**Comment by Stehsaer** [comment]
> 您好，首先请确认发生问题的进程是 frpc（注意c），还是有头像图标的启动器。
> 
> 如果是启动器，我们在最近的 [commit](https://github.com/natfrp/SakuraFrpLauncher/commit/0bc56547b77e6ab7be17fa484e17bfdd0d46cfab) 修复了一个可能的内存泄露问题，但是暂时还没有发布。
> 如果您没有自己编译dev分支的工具的话，可以选择不要让启动器常驻后台，在启动需要的隧道后右击启动器图标，选择 “退出启动器” 即可，隧道会继续工作，再次打开启动器即可查看运行情况等。
> 
> 如果是frpc的话，目前您的问题我们无法复现，如果您可以在发生问题的时候打开 任务管理器 - “详细信息” 找到出现问题的进程，右键创建转储文件，然后联系我们的话，将大大提前我们发现问题的进程。

发生问题的是frp启动器。我这边目前也无法复现该问题，这是我用sakurafrp一年多以来第一次出现该问题。报到issue的主要原因是这个问题影响太大 QAQ 。
希望 [commit](https://github.com/natfrp/SakuraFrpLauncher/commit/0bc56547b77e6ab7be17fa484e17bfdd0d46cfab) 能修复这个问题。无论如何，谢谢sakurafrp的各位开发者们为我们带来优秀的内网穿透体验

**Comment by Stehsaer** [comment]
> 您好，首先请确认发生问题的进程是 frpc（注意c），还是有头像图标的启动器。
> 
> 如果是启动器，我们在最近的 [commit](https://github.com/natfrp/SakuraFrpLauncher/commit/0bc56547b77e6ab7be17fa484e17bfdd0d46cfab) 修复了一个可能的内存泄露问题，但是暂时还没有发布。
> 如果您没有自己编译dev分支的工具的话，可以选择不要让启动器常驻后台，在启动需要的隧道后右击启动器图标，选择 “退出启动器” 即可，隧道会继续工作，再次打开启动器即可查看运行情况等。
> 
> 如果是frpc的话，目前您的问题我们无法复现，如果您可以在发生问题的时候打开 任务管理器 - “详细信息” 找到出现问题的进程，右键创建转储文件，然后联系我们的话，将大大提前我们发现问题的进程。

发生问题的是frp启动器。我这边目前也无法复现该问题，这是我用sakurafrp一年多以来第一次出现该问题。报到issue的主要原因是这个问题影响太大 QAQ 。
希望 [commit](https://github.com/natfrp/SakuraFrpLauncher/commit/0bc56547b77e6ab7be17fa484e17bfdd0d46cfab) 能修复这个问题。无论如何，谢谢sakurafrp的各位开发者们为我们带来优秀的内网穿透体验

**Comment by Stehsaer** [comment]
问题再次出现，这次有截图了。无法创建转储文件（持续了很久都没法创建）
![image](https://user-images.githubusercontent.com/54050160/139624400-171c4350-69c2-498b-88cb-670d1a42b28b.png)
