### ISSUE TITLE
关于客户端头像问题/issues on user's profile picture

### ISSUE THREAD

**Issue by zkj12340** [fengberd/SakuraFrpLauncher#13]
当我觉得客户端这张超大二次元头像有一点羞耻，然后快速点击了三下后，就变成了一个红色漩涡，再点几下变成了粉色漩涡加白色齿轮，我又想换回原来的早苗，结果发现怎么也回不去了……到底怎么把头像换回去啊？这是告诉我们失去了才知道珍惜吗？

When I feel this large two-dimensional profile picture is a little shaming, and then quickly click it for three times, it became a red whirlpool, and again turned to a pink whirlpool with white gear, I want to change back to the original Zao Miao one, it turns out that it is impossible, how the hell can I go back now..... Does this tell us that we don't know how to cherish until we've lost it?

**Comment by fakeboboliu** [comment]
最简单的方法：可以清空此应用的设置项来重置

在右下角托盘处关闭客户端后，清空 `%localappdata%/SakuraLauncher` 中的内容即可

如果有兴趣的话也可以自己修改

**Comment by zkj12340** [comment]
太好了已经解决：
setting name="LogoIndex" serializeAs="String" value  0  /value
这一项改为 0 即可，1是红漩涡，2是粉漩涡

另外，软件很好用，和朋友联机成功，一天都很开心~
