### ISSUE TITLE
WOL 隧道创建后，如何通过命令行唤醒。

### ISSUE THREAD

**Issue by shinoi2** [fengberd/SakuraFrpLauncher#15]
![2021-10-25 09-59-35 的屏幕截图](https://user-images.githubusercontent.com/26739043/138623673-e8d15188-a727-4c3f-8edd-7fb86dbf66b5.png)

natfrp 可以通过网页端点击开机，请问是否可以命令行方式进行开机 ?
例如: `wakeonlan -i $IP_address $MAC_address`

**Comment by fakeboboliu** [comment]
![image](https://user-images.githubusercontent.com/7552030/138426801-003361a8-b9de-471d-9285-0146fb183fcc.png)

你好，你可以通过标题右边的按钮继续编辑标题，或内容下拉菜单中的编辑继续编辑此 issue 的内容

**Comment by shinoi2** [comment]
Are there any updates?
