### ISSUE TITLE
Administrator 账户在开启特定组策略后无法自动请求提权

### ISSUE THREAD

**Issue by MyBlueHorizon** [fengberd/SakuraFrpLauncher#17]
系统：Windows Server 2016
详细描述：开启 “用户帐户控制: 对内置管理员帐户使用管理审批模式” 后，启动器无法正常请求权限，必须右键管理员身份运行。
预期：可以开启时自动请求管理员权限。

**Comment by fakeboboliu** [comment]
使用 Windows Server 2016 Standard (14393.2273) 测试并未复现。
