### ISSUE TITLE
大佬,编译失败该怎么解决

### ISSUE THREAD

**Issue by fenglinya-it** [fengberd/SakuraFrpLauncher#19]
系统:Windows 10

**Comment by fenglinya-it** [comment]
<img width="918" alt="{7F65E6B8-CADE-4905-AB2C-9C29DE6BDC09}" src="https://github.com/natfrp/SakuraFrpLauncher/assets/128617097/3f5cdf1d-c88b-4fb9-92b9-b08842331795">

**Comment by fakeboboliu** [comment]
你忘了 protoc

另：我们不提供编译帮助，如果自己配置有困难请参考我们使用的 github actions 配置，或者直接使用 actions 进行构建。
