### ISSUE TITLE
有考虑过像旧版SakuraLauncher一样记住登陆密钥吗（问题已解决）

### ISSUE THREAD

**Issue by Just-Prog** [fengberd/SakuraFrpLauncher#2]
旧版的这个功能相当好使啊啊啊啊啊啊啊啊啊啊
如果采纳，定要感谢

不好意思，刚看到可以保存连接密钥
我描述的是上个版本的问题
非常抱歉打扰了
大大可以Close了
（另外作为GIT新手想问一下，我自己个人能不能关掉这个issue）

**Comment by fengberd** [comment]
重启后不会自动登录?
这是一个Bug, 请给出具体重现步骤
