### ISSUE TITLE
有考虑过加个配置开关吗？

### ISSUE THREAD

**Issue by coderzhw** [fengberd/SakuraFrpLauncher#3]
目前只能通过添加tls_enable = true，然后用frpc.exe启动，能否在这个客户端加个这个开关呢？

**Comment by fengberd** [comment]
frpc支持这个么
@kagurazakasanae

**Comment by coderzhw** [comment]
> frpc支持这个么
> @kagurazakasanae

目前我用这个客户端登不上，只能通过在frpc.ini里面加上tls_enable = true之后才能正常使用，然后又得折腾windows服务自启动，啥的，要不然一个cmd窗口很不方便，希望能在客户端加上这个配置参数

**Comment by fengberd** [comment]
如果你说的是frpc.exe的事情, 那个与我无关, 请联系 @kagurazakasanae
我只维护这个项目对应的启动器

**Comment by kagurazakasanae** [comment]
目前没有计划添加对tls启动选项的支持
