### ISSUE TITLE
希望可以增加日志提醒功能

### ISSUE THREAD

**Issue by adenlin0812** [fengberd/SakuraFrpLauncher#4]
额，就是有log的时候弹一下小窗口提示。
如果up主觉得这个功能有必要做但是又没时间做的话我可以提交一份pull request哦

**Comment by fengberd** [comment]
由于 frpc 日志较多，该功能可能产生大量无意义弹窗打扰用户，因此不做考虑
目前启动器已经会弹窗提示部分不符合日志格式的提示，如连接成功、frpc崩溃等，后期可能加入其他关键通知告知用户当前状态，但也是以其他方式进行展现而不是进行弹窗

**Comment by adenlin0812** [comment]
> 由于 frpc 日志较多，该功能可能产生大量无意义弹窗打扰用户，因此不做考虑
> 目前启动器已经会弹窗提示部分不符合日志格式的提示，如连接成功、frpc崩溃等，后期可能加入其他关键通知告知用户当前状态，但也是以其他方式进行展现而不是进行弹窗

嗯，我看到日志好像有分类的，比如[E]这样子，最好是能够提示一下啦
