### ISSUE TITLE
麻烦问一下，现在SakuraLauncher可以看frp的Dashboard吗

### ISSUE THREAD

**Issue by dupeng0811** [fengberd/SakuraFrpLauncher#5]
看到frp文档有写dashboard是7500端口，我访问后提示要输入账号和密码，不知道SakuraLauncher这里支持吗，支持的话那登录的账号密码是什么呢，谢谢。

在使用frp内网穿透来做微信开发，有时候要看一下请求的参数什么的，谢谢！

**Comment by dupeng0811** [comment]
试过admin/admin是不行的。访问密钥/访问密钥也是进不去的~~

**Comment by fengberd** [comment]
启动器暂不支持此功能，如有使用需求请使用配置文件开启frpc并手动配置管理面板

**Comment by dupeng0811** [comment]
但是这个我看都是在服务器端添加的。怎么在客户端配置有文档吗？谢谢


给 FRP 服务端增加一个 Dashboard
通过 Dashboard 可以方便的查看 FRP 的状态以及代理统计信息展示，要使用这个功能首先需要在 FRP 服务端配置文件中指定 Dashboard 服务使用的端口：
```
$ vim frps.ini

[common]

# 指定 Dashboard 的监听的 IP 地址
dashboard_addr = 0.0.0.0

# 指定 Dashboard 的监听的端口
dashboard_port = 7500

# 指定访问 Dashboard 的用户名
dashboard_user = admin

# 指定访问 Dashboard 的端口
dashboard_pwd = admin
```

**Comment by fengberd** [comment]
服务端/客户端均有内置 Dashboard
参考资料: https://github.com/fatedier/frp#dashboard
另请参阅: https://github.com/fatedier/frp#admin-ui
