### ISSUE TITLE
建议：能不能在网页端增加一列，直接显示穿透后的网址，那样就点一下直接打开了，省的复制

### ISSUE THREAD

**Issue by better319** [fengberd/SakuraFrpLauncher#8]
。。。懒了点，但是确实实用。
另又方便点的docker介绍吗，适合群晖的更好，谢谢！

**Comment by fengberd** [comment]
我们会考虑这个功能, 但是你应该到 OWQ 的 issue 频道发这个问题,这是启动器仓库

docker 镜像仍在开发中

**Comment by fakeboboliu** [comment]
刚好看到了，就回复下，这里是 docker： https://doc.natfrp.com/#/frpc/service/docker
